-- Añade VERDE_CON_ALERTAS al semáforo (D-019, docs/decisions.md).
--
-- El semáforo pasa de tres colores más GRIS a cuatro colores más GRIS:
-- VERDE_CON_ALERTAS se sitúa entre VERDE y AMBAR, para los proyectos que
-- cumplen los mínimos y son defendibles pero conservan algún defecto
-- importante -típicamente, algún hallazgo P3 fiable sin ningún P1 ni P2-.
-- El backend ya lo escribe así (`backend/salidas/informe.py`,
-- `CODIGOS_SEMAFORO`); esta migración es la que hace que
-- `correccion.semaforo_propuesto` y `correccion.semaforo_aprobado` -las dos
-- columnas tipadas `semaforo`, `supabase/migrations/
-- 20260827120000_esquema_inicial.sql`- acepten ese valor sin que PostgREST
-- rechace la fila.
--
-- No se retira ningún valor existente ni se reordena el enum: los cuatro
-- colores previos (VERDE, AMBAR, ROJO, GRIS) siguen exactamente igual.
--
-- 'VERDE_CON_ALERTAS' no es todavía un nivel formal del §12.1 del Documento
-- Maestro -ver D-019 y el criterio en criteria/v2026-2027/semaforo.yaml para
-- el porqué y el hueco que queda pendiente de que el docente lo cierre-.
--
-- Aplicación: el docente la ejecuta desde el panel de Supabase, no un token
-- personal (instrucción permanente del proyecto). 'ALTER TYPE ... ADD VALUE'
-- no admite transacción compartida con su propio uso posterior: esta
-- migración solo añade el valor y no lo usa en la misma sentencia.

alter type semaforo add value if not exists 'VERDE_CON_ALERTAS' after 'VERDE';
